branches:
  only:
    - master
environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
services:
  - mongodb
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm test
