name: Node CI

on:
  pull_request:
    branches:
    - master
    - v5.x

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.20.1, 16.0.0, 18.0.0]
        mongodb: [6.0, 7.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-replica-set: test
        mongodb-version: ${{ matrix.mongodb }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
