name: Node CI

on:
  pull_request:
    branches:
    - master
    - v6.x

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.20.1, 18.0.0, 20.0.0, 22.0.0, 24.0.0]
        mongodb: [6.0, 7.0, 8.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.1
      with:
        mongodb-replica-set: test
        mongodb-version: ${{ matrix.mongodb }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
